[project]
name = "worldbank-subnational-poverty-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopandas>=1.1.2",
    "geopy>=2.4.1",
    "jupyter>=1.1.1",
    "pandas>=3.0.0",
]
